---

- name: install sshpass for ssh connection
  command: "sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/sshpass-1.06-2.el7.x86_64.rpm"
  become: yes
  
- name: set credentials for ssh connection
  command: "ansible localhost -m {{ rg_group }} -a {{ ansible_params }}"
  become: yes

- name: Set timezone to west EU
  timezone:
    name: Europe/Madrid
  become: yes

- name: enable epel repository
  command: "/usr/bin/dnf -y install {{ epel_repo }}"
  become: yes

- name: install packages
  dnf:
    name: "{{ rpms }}"
    state: latest
  become: yes

- name: enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  with_items:
    - "{{ services }}"

- name: firewall configuration
  systemd:
    name: "{{ item }}"
    permanent: yes
    state: enabled
    inmediate: yes
  become: yes
  with_items:
    - "{{ fw_services }}"