---

#install 'chrony', 'bind-utils', 'nmap', 'dnf-plugins-core', 
#'elinks', 'net-tools', 'jq' and 'dive'

- name: enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  with_items:
    - "{{ services }}"

#firewall configuration
- name: firewall configuration
  systemd:
    name: "{{ item }}"
    permanent: yes
    state: enabled
    inmediate: yes
  become: yes
  with_items:
    - "{{ fw_services }}"