- name: enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  with_items:
    - "{{ services }}"

- name: firewall configuration
  systemd:
    name: "{{ item }}"
    permanent: yes
    state: enabled
    inmediate: yes
  become: yes
  with_items:
    - "{{ fw_services }}"