---

#install git in machines and clone repo
- name: install git
  command: "sudo dnf install git -y"
  become: yes

- name: clone case2 repo
  git:
    repo: "https://@github.com/{{ user }}/{{ repo_name }}.git"
    dest: "{{ target_dir }}"
  no_log: true