---

#docker configuration, installation and deploy

- name: docker configuration
  command: "/usr/bin/dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  become: yes

- name: install docker-ce
  dnf:
    name: docker-ce
    state: present
  become: yes

- name: configure and deploy docker
  systemd:
    name: mydocker
    image: wordpress
    state: started
    enabled: yes
    ports: 9000
  become: yes
